### PR TITLE
brainglobe_space name change

### PR DESCRIPTION
**Pull request by sfmig**
Update references to brainglobe_space in brainmapper after name change.

### CODE REVIEW

**Review by willGraham01 — COMMENTED** [review]
:+1: 

Though the segmentation fault is not a pleasant thing to see. Nor do I expect to see it since nothing is actually changing :thinking: Could be a pytest-related thing?

**Comment by adamltyson** [comment]
Presumably it is the same issue considering brainmapper uses cellfinder?

**Comment by willGraham01** [comment]
> Presumably it is the same issue considering brainmapper uses cellfinder?

We've since released a version of cellfinder that has that patch in it. But it seems that a re-run has fixed this problem? I'm very confused!

**Comment by sfmig** [comment]
yep I was concerned too (and mixed feelings about how re-running fixed it...)

**Pull request merged**
